### ISSUE TITLE
Source map line in jsoneditor.min.js makes collectstatic fail

### ISSUE THREAD

**Issue by hnykda** [jmrivas86/django-json-widget#63] opened 2021-12-21 10:51 UTC
* django-json-widget version: 1.1.1
* Django version: 4.0
* Python version: 3.8.10
* Operating System: linux ubuntu (in docker)

### Description
When running `python manage.py collectstatic` with whitenoise 5.3.0, I get the following error:

```
es/management/commands/collectstatic.py", line 134, in collect
remote:            raise processed
remote:        whitenoise.storage.MissingFileError: The file 'dist/jsoneditor.map' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x7f260dc431f0>.
remote:        The JS file 'dist/jsoneditor.min.js' references a file which could not be found:
remote:          dist/jsoneditor.map
```

it seems it's because of the source map bit. When we removed the last line https://github.com/jmrivas86/django-json-widget/blob/master/django_json_widget/static/dist/jsoneditor.min.js#L46 , it works.

**Comment by Sus-Bierbaum** [comment] 2022-03-07 09:49
I get the same error. For me simply removing the last line, does not resolve the problem. I am still getting the same error

**Comment by shacker** [comment] 2022-03-15 21:04
Confirmed - this is blocking our upgrade to Django 4.x. Any progress?

**Comment by Sus-Bierbaum** [comment] 2022-03-18 07:25
I started deleting the line everytime I am building my docker image now after I went back to Django 3.2.x. It is really frustrating and time consuming. So the solution above seems to work for 3.2.x but not for newer versions. I'm not quite sure why this last line is even in there, if it works without the line.

**Comment by shacker** [comment] 2022-03-19 06:17
For typical build systems, deleting a line isn't an option - everything is pulled from the cloud and built in real time, with no human intervention, on many servers at once. Getting a little concerning that no one has responded on this thread. Is this package still maintained?

**Comment by FroguelObramax** [comment] 2022-09-01 11:31
Has anyone found a workaround of this issue? I'm facing the same here and because of it I am not able to use this package. I found in SO how to do basic formatting, but that is nothing in comparison to this package,which is pretty good. Maybe someone did a fork with a correction that I did not find?

**Comment by FroguelObramax** [comment] 2022-09-01 12:14
I actually found a way to deal with this issue, if anyone ever comes here again. He asks for a file which he does not use, so I decided to just put the file where he expects it and it worked like a charm. I am building my project with a Dockerfile, so I just added there 
```
COPY random/jsoneditor.map /usr/local/lib/python3.9/site-packages/django_json_widget/static/dist
```
the file may be empty. It is not the prettiest solution, but it does work. Hope it helps someone else.

**Comment by josebsneto** [comment] 2022-09-23 20:58
I have the same problem. Already have a native solution?

**Comment by dmwyatt** [comment] 2022-11-06 19:24
> I actually found a way to deal with this issue, if anyone ever comes here again. He asks for a file which he does not use, so I decided to just put the file where he expects it and it worked like a charm. I am building my project with a Dockerfile, so I just added there
> 
> ```
> COPY random/jsoneditor.map /usr/local/lib/python3.9/site-packages/django_json_widget/static/dist
> ```
> 
> the file may be empty. It is not the prettiest solution, but it does work. Hope it helps someone else.

It's so terrible, I love it.

Here's a one-liner to do the same thing.

```bash
python -c "import django_json_widget as _; from pathlib import Path; p=Path(_.__path__[0]) / 'static' / 'dist' / 'jsoneditor.map'; p.touch()"
```

This accounts for different package installation paths and whatnot...I use it in CI/CD environment.


Really someone needs to submit a PR to fix this.  However, @jmrivas86 hasn't been active on GH in many months and his website doesn't work, so not sure if we can expect a PR to get merged.  Failing that someone will have to fork...

**Comment by fabiocaccamo** [comment] 2023-03-29 15:42
While waiting for #70 to be merged, you can avoid this exception globally by using a custom `STATICFILES_STORAGE`:
```python
from django.contrib.staticfiles.storage import ManifestStaticFilesStorage


class ManifestStaticFilesStorageNotStrict(ManifestStaticFilesStorage):
    
    def hashed_name(self, name, content=None, filename=None):
        try:
            return super().hashed_name(name, content=content, filename=filename)
        except ValueError:
            return name
```

**Comment by jmrivas86** [comment] 2023-10-06 23:10
Fixed in https://github.com/jmrivas86/django-json-widget/pull/70

**Closed by jmrivas86** 2023-10-06 23:10 UTC
